language: python

env:
  - DJANGO_SECRET_KEY=1

python:
  - "3.4"

install:
 - pip install -r requirements.txt
 - cd push_server/
 - npm install
 - cd ..

script:
  - (node push_server/server.js) &
  - python ./manage.py collectstatic --noinput
  - python ./manage.py test -v 3
