# List of API Errnos

USERNAME_OR_PASSWORD_NONE = 201
NOT_AUTHENTICATED_AS_PROJECT = 202
INVALID_MESSAGE_STRUCTURE = 203
INVALID_PROJECT_ID = 204
INVALID_PROJECT_AUTHENTICATION = 205
INSUFFICIENT_PROJECT_PERMISSIONS = 206

MAGNETIC_INVALID_ID = 250
MAGNETIC_NO_MEMBER = 251

RFID_NO_MEMBER = 261

EMPTY_POST = 300
