# List of API Errnos

USERNAME_OR_PASSWORD_NONE = 201
NOT_AUTHENTICATED_AS_PROJECT = 202
NOT_AUTHENTICATED_AS_THIS_PROJECT = 202
INVALID_MESSAGE_STRUCTURE = 203
INVALID_PROJECT_ID = 204
INVALID_PROJECT_AUTHENTICATION = 205